//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 11:20:11 AM COT 
//


package co.mil.ejercito;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cedula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="apellidos" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2"/>
 *         &lt;element name="grado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Unidad"/>
 *         &lt;element ref="{}Ausencia" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cedula",
    "nombre",
    "apellidos",
    "grado",
    "unidad",
    "ausencia"
})
@XmlRootElement(name = "Empleado")
public class Empleado {

    @XmlElement(required = true)
    protected String cedula;
    @XmlElement(required = true)
    protected List<String> nombre;
    @XmlElement(required = true)
    protected List<String> apellidos;
    @XmlElement(required = true)
    protected String grado;
    @XmlElement(name = "Unidad", required = true)
    protected Unidad unidad;
    @XmlElement(name = "Ausencia", required = true)
    protected List<Ausencia> ausencia;          //lista porque puede tener muchas ausencias

    /**
     * Gets the value of the cedula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCedula() {
        return cedula;
    }

    /**
     * Sets the value of the cedula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCedula(String value) {
        this.cedula = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nombre property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNombre().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNombre() {
        if (nombre == null) {
            nombre = new ArrayList<String>();
        }
        return this.nombre;
    }

    /**
     * Gets the value of the apellidos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apellidos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApellidos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getApellidos() {
        if (apellidos == null) {
            apellidos = new ArrayList<String>();
        }
        return this.apellidos;
    }

    /**
     * Gets the value of the grado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrado() {
        return grado;
    }

    /**
     * Sets the value of the grado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrado(String value) {
        this.grado = value;
    }

    /**
     * Gets the value of the unidad property.
     * 
     * @return
     *     possible object is
     *     {@link Unidad }
     *     
     */
    public Unidad getUnidad() {
        return unidad;
    }

    /**
     * Sets the value of the unidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unidad }
     *     
     */
    public void setUnidad(Unidad value) {
        this.unidad = value;
    }

    /**
     * Gets the value of the ausencia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ausencia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAusencia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ausencia }
     * 
     * 
     */
    public List<Ausencia> getAusencia() {
        if (ausencia == null) {
            ausencia = new ArrayList<Ausencia>();
        }
        return this.ausencia;
    }

}
